## Numpy
Import Library Numpy

In [2]:
import numpy as np

Membuat Matriks (Baris, Kolom) bernilai 1

In [3]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Membuat Matriks (Baris, Kolom) Bernilai 0

In [4]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

LineSpace(Awal, Akhir, Jumlah Value dalam Array) Note : Tipe data : Float

In [5]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

Membuat Identity Matriks | eye(Baris&Kolom)

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random Value
Rand = Memberikan nilai float secara acak bernilai 0 sampai 1 | rand(Jumlah Value) | rand(Baris, Kolom)

In [7]:
np.random.rand(2)

array([0.34380771, 0.31566387])

In [8]:
np.random.rand(2, 3)

array([[0.83788441, 0.18760639, 0.79309199],
       [0.13950974, 0.95995641, 0.82271426]])

randn = Memberikan nilai float secara acak standar normal | randn(Jumlah Value) | randn(Baris, Kolom)

In [9]:
np.random.randn(2)

array([-0.22139675,  0.86357027])

In [10]:
np.random.randn(2, 3)

array([[ 0.48431224, -0.41751862, -0.59313733],
       [ 1.25361019,  0.96249589, -1.18725662]])

Membuat Array Matriks | Arange(Batas) = Nilai dari 0 sampai < batas | Reshape(Baris, Kolom)

In [11]:
arr = np.arange(50).reshape(5, 10)

In [12]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Cara mengambil Nilai dalam sebuah Array Numpy | arr[Baris=1 : Kolom=3 , Baris= <3 : Kolom= <5]
Note : Pengurangan 1 karena index yang dibaca < batas

In [13]:
arr[1:3,3:5]

array([[13, 14],
       [23, 24]])

### Mengambil Nilai Terkecil, Terbesar, Nilai Index Terkecil, Nilai Index Terbesar

In [15]:
arr2 = np.array([3, 4, 6, 2, 10])

In [17]:
arr2.max() #Nilai Terbesar

10

In [18]:
arr2.min() #Nilai Terkecil

2

In [21]:
arr2.argmin() #Nilai Index Terkecil (Nilai 3 didapat dari letak nilai terkecil dari sebuah array)

3

In [22]:
arr2.argmax() #Nilai Index Terbesar (Nilai 4 didapat dari letak nilai terbesar dari sebuah array)

4

### Broadcasting

In [23]:
arr3 = np.arange(0,11)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Merubah Nilai pada index array | arr[Index awal : Index akhir]
arr3[0:5] = 100
arr3

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [32]:
#Array reset
arr3 = np.arange(0,11)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Hati - hati dalam memberikan nilai array pada variable baru

In [29]:
copy_arr = arr3
copy_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# Merubah Copy_arr
copy_arr[0:6] = 20
copy_arr

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10])

Disaat anda merubah variable array baru, array lama akan ikut terganti

In [31]:
arr3

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10])

Cara mengatasi hal tersebut

In [35]:
arr3 = np.arange(0,11)

copy_arr = arr3.copy() #Fungsi .copy() untuk menyalin data array lama ke variable array yang baru
copy_arr[0:6] = 20 #Merubah Nilai

#Show
print("Copy_arr = \n", copy_arr) #Variable Array Baru
print("Array = \n", arr3) #Variable Array Lama

Copy_arr = 
 [20 20 20 20 20 20  6  7  8  9 10]
Array = 
 [ 0  1  2  3  4  5  6  7  8  9 10]
